services:
  boinc:
    image: ghcr.io/shufflebox/wcg-client:latest
    container_name: boinc
    restart: unless-stopped
    volumes:
      - ./boinc_data:/var/lib/boinc

    environment:
      - WCG_ACCOUNT_KEY=${WCG_ACCOUNT_KEY}
    
    # Resource controls
    #cpus: 2.0
    #mem_limit: 4g
